force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Education</relationshipLabel>
    <relationshipName>Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_About__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_About__c</fullName>
    <label>About</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Company__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Company__c</fullName>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Headline__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Headline__c</fullName>
    <label>Headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>These are Prospect records in the data pool that everybody can see and approach</description>
    <label>Prospect (Lead database)</label>
</RecordType>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Experience No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/License_and_Certifications__c.object-meta.xml
<CustomObject>
    <label>License and Certification</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License and Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_and_Certifications__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>Licenses_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>License_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/Prospect_Landing_Zone__c.object-meta.xml
<CustomObject>
    <label>Prospect Landing Zone</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects Landing Zone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>Headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/Linkedin_About_Me__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_About_Me__c</fullName>
    <label>Linkedin About Me</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <externalId>true</externalId>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ESC_NBC_ProspectLandingZoneBatch.cls
/**
* @File Name : NBC_ESC_ProspectLandingZoneProcessor.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : February 14, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | February 14, 2025 |   | Initial Version
**/
// Database.executeBatch(new ESC_NBC_ProspectLandingZoneBatch());
public class ESC_NBC_ProspectLandingZoneBatch implements Database.batchable<sObject>{
 
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'select firstName__c,lastName__c,headline__c,url__c,Linkedin_About_Me__c  from Prospect_Landing_Zone__c where Processed__c = false';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Prospect_Landing_Zone__c> scope)
    {
        list<string> urls = new list<string>();
        map<string,string> linkedinURLToLeadId = new map<string,string>();
        list<ESC_NBC_Prospect__c>  prospectsToUpsert = new list<ESC_NBC_Prospect__c>();
        for(Prospect_Landing_Zone__c pl : scope)
        {
            urls.add(pl.url__c);
            pl.Processed__c = true;
        }
        for(ESC_NBC_Prospect__c prospectObj : [select id,ESC_NBC_Linkedin_URL__c from ESC_NBC_Prospect__c where ESC_NBC_Linkedin_URL__c in: urls])
        {
            linkedinURLToLeadId.put(prospectObj.ESC_NBC_Linkedin_URL__c, prospectObj.id);
        }
        String prospectRecordTypeId = [select Id, NAME from RECORDTYPE where SobjectType = 'ESC_NBC_Prospect__c' AND DeveloperName = 'Prospect'][0].Id;
        for(Prospect_Landing_Zone__c pl : scope)
        {
            String nameFinal = '';
            if(pl.firstName__c != null && !String.isBlank(pl.firstName__c)) {
                nameFinal = pl.firstName__c;
            }
            if(pl.lastName__c != null && !String.isBlank(pl.lastName__c)) {
                nameFinal += pl.lastName__c;
            }  
            ESC_NBC_Prospect__c prospectObj = new ESC_NBC_Prospect__c(
                Name = nameFinal,
                ESC_NBC_Headline__c = pl.headline__c,
                ESC_NBC_About__c = pl.Linkedin_About_Me__c,
                ESC_NBC_Linkedin_URL__c = pl.url__c,
                ESC_NBC_Company__c = 'Linkedin Scrapped Data',
                RecordTypeId = prospectRecordTypeId
            );
            if(linkedinURLToLeadId.containsKey(pl.url__c))
            {
                prospectObj.id = linkedinURLToLeadId.get(pl.url__c);
            }
             prospectsToUpsert.add(prospectObj);
        }
        upsert  prospectsToUpsert;
        for(ESC_NBC_Prospect__c prospectObj :  prospectsToUpsert)
        {
            linkedinURLToLeadId.put(prospectObj.ESC_NBC_Linkedin_URL__c, prospectObj.id);
        }
        list<Experience__c> exp = [Select id,Prospect_Landing_Zone__r.url__c from Experience__c where Prospect_Landing_Zone__r.url__c =: linkedinURLToLeadId.keyset()];
        list<Education__c> edu = [Select id,Prospect_Landing_Zone__r.url__c from Education__c where Prospect_Landing_Zone__r.url__c =: linkedinURLToLeadId.keyset()];
        list<License_and_Certifications__c> lc = [Select id,Prospect_Landing_Zone__r.url__c from License_and_Certifications__c where Prospect_Landing_Zone__r.url__c =: linkedinURLToLeadId.keyset()];
        list<Organization__c> org = [Select id,Prospect_Landing_Zone__r.url__c from Organization__c where Prospect_Landing_Zone__r.url__c =: linkedinURLToLeadId.keyset()];
        
        for(Experience__c e : exp)
        {
            e.ESC_NBC_Prospect__c = linkedinURLToLeadId.get(e.Prospect_Landing_Zone__r.url__c);
        }
        for(Education__c e : edu)
        {
            e.ESC_NBC_Prospect__c = linkedinURLToLeadId.get(e.Prospect_Landing_Zone__r.url__c);
        }
        for(License_and_Certifications__c l : lc)
        {
            l.ESC_NBC_Prospect__c = linkedinURLToLeadId.get(l.Prospect_Landing_Zone__r.url__c);
        }  
        for(Organization__c o : org)
        {
            o.ESC_NBC_Prospect__c = linkedinURLToLeadId.get(o.Prospect_Landing_Zone__r.url__c);
        }
        update exp;
        update edu;
        update lc;
        update org;
        update scope;
    }

    public void finish(Database.BatchableContext BC) {
    
    }
}