force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Education</relationshipLabel>
    <relationshipName>Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>These are Prospect records in the data pool that everybody can see and approach</description>
    <label>Prospect (Lead database)</label>
</RecordType>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Experience No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/License_and_Certifications__c.object-meta.xml
<CustomObject>
    <label>License and Certification</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License and Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_and_Certifications__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>Licenses_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>License_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/ESC_NBC_Prospect__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/Prospect_Landing_Zone__c.object-meta.xml
<CustomObject>
    <label>Prospect Landing Zone</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects Landing Zone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>Headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/Linkedin_About_Me__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_About_Me__c</fullName>
    <label>Linkedin About Me</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <externalId>true</externalId>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NBC_ESC_ProspectLandingZoneBatch_Test.cls
@isTest
public class NBC_ESC_ProspectLandingZoneBatch_Test {
    @testSetup
    static void setupTestData() {
        String uniqueURL = 'https://linkedin.com/test';
        // Create test Prospect Landing Zone records
        Prospect_Landing_Zone__c prospect = new Prospect_Landing_Zone__c(
            firstName__c = 'TestFirst',
            lastName__c = 'TestLast',
            headline__c = 'Test Headline ',
            url__c = uniqueURL,
            Linkedin_About_Me__c = 'Test About Me ',
            Processed__c = false
        );
        insert prospect;
        
         // Insert related child records and link to the Prospect Landing Zone
        Experience__c experience = new Experience__c(
            Sequence__c =1,
            Prospect_Landing_Zone__c = prospect.Id
        );
        Education__c education = new Education__c(
            Name = 'EDU-001',
            Sequence__c = 1,
            Prospect_Landing_Zone__c = prospect.Id
        );
        License_and_Certifications__c licenseCert = new License_and_Certifications__c(
            Name = 'LICAC-001',
            Sequence__c = 1,
            Prospect_Landing_Zone__c = prospect.Id
        );
        Organization__c organization = new Organization__c(
            Name = 'ORG-001',
            Prospect_Landing_Zone__c = prospect.Id
        );
        
        insert experience;
        insert education;
        insert licenseCert;
        insert organization;
    }

    @isTest
    static void testBatchExecution() {
        Test.startTest();
        ESC_NBC_ProspectLandingZoneBatch batchJob = new ESC_NBC_ProspectLandingZoneBatch();
        Database.executeBatch(batchJob);
        Test.stopTest();

        // Validate that all records are processed
        List<Prospect_Landing_Zone__c> processedRecords = [SELECT Id, Processed__c FROM Prospect_Landing_Zone__c];
        for (Prospect_Landing_Zone__c record : processedRecords) {
            System.assert(record.Processed__c, 'Processed__c should be true');
        }

        // Validate that new prospects are inserted and existing ones are updated
        List<ESC_NBC_Prospect__c> allProspects = [SELECT Id, Name, ESC_NBC_Linkedin_URL__c FROM ESC_NBC_Prospect__c];
        System.assertEquals(1, allProspects.size(), 'There should be 1 ESC_NBC_Prospect__c records after processing');
    }
}