force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Education</relationshipLabel>
    <relationshipName>Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Education</relationshipLabel>
    <relationshipName>Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Experience No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/License_and_Certifications__c.object-meta.xml
<CustomObject>
    <label>License and Certification</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License and Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_and_Certifications__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>License_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_and_Certifications__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>License and Certifications</relationshipLabel>
    <relationshipName>License_and_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Prospect_Landing_Zone__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Landing_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Landing Zone</label>
    <referenceTo>Prospect_Landing_Zone__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/Prospect_Landing_Zone__c.object-meta.xml
<CustomObject>
    <label>Prospect Landing Zone</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects Landing Zone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/headline__c.field-meta.xml
<CustomField>
    <fullName>headline__c</fullName>
    <label>Headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/Linkedin_About_Me__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_About_Me__c</fullName>
    <label>Linkedin About Me</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Prospect_Landing_Zone__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <externalId>true</externalId>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/processCandidateLandingData.cls
/**
* @File Name : processCandidateLandingData.cls
* @Description : Batch to process prospect landing records into leads  
* @Author : Digvijay
* @Last Modified By :
* @Last Modified On : October 16, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 16, 2024 |   | Initial Version
**/
public class processCandidateLandingData implements Database.batchable<sObject>{ 
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'select firstName__c,lastName__c,headline__c,url__c,Linkedin_About_Me__c  from Prospect_Landing_Zone__c where Processed__c = false';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Prospect_Landing_Zone__c> scope)
    {
        list<string> urls = new list<string>();
        map<string,string> urlLeads = new map<string,string>();
        list<lead> leadsToInsert = new list<lead>();
        for(Prospect_Landing_Zone__c pl : scope)
        {
            urls.add(pl.url__c);
            pl.Processed__c = true;
        }
        for(lead l : [select id,Linkedin_URL__c from lead where Linkedin_URL__c in: urls])
        {
            urlLeads.put(l.Linkedin_URL__c, l.id);
        }
        for(Prospect_Landing_Zone__c pl : scope)
        {
            Lead l = new Lead();
            l.FirstName = pl.firstName__c;
            l.LastName = pl.lastName__c;
            l.headline__c = pl.headline__c;
            l.About__c = pl.Linkedin_About_Me__c;
            l.Linkedin_URL__c = pl.url__c;
            l.company = 'Linkedin Scrapped Data';
            if(urlLeads.containsKey(pl.url__c))
            {
                l.id = urlLeads.get(pl.url__c);
            }
            leadsToInsert.add(l);
        }
        upsert leadsToInsert;
        for(lead l : leadsToInsert)
        {
            urlLeads.put(l.Linkedin_URL__c, l.id);
        }
        list<Experience__c> exp = [Select id,Prospect_Landing_Zone__r.url__c from Experience__c where Prospect_Landing_Zone__r.url__c =: urlLeads.keyset()];
        list<Education__c> edu = [Select id,Prospect_Landing_Zone__r.url__c from Education__c where Prospect_Landing_Zone__r.url__c =: urlLeads.keyset()];
        list<License_and_Certifications__c> lc = [Select id,Prospect_Landing_Zone__r.url__c from License_and_Certifications__c where Prospect_Landing_Zone__r.url__c =: urlLeads.keyset()];
        list<Organization__c> org = [Select id,Prospect_Landing_Zone__r.url__c from Organization__c where Prospect_Landing_Zone__r.url__c =: urlLeads.keyset()];
        
        for(Experience__c e : exp)
        {
            e.Lead__c = urlLeads.get(e.Prospect_Landing_Zone__r.url__c);
        }
        for(Education__c e : edu)
        {
            e.Lead__c = urlLeads.get(e.Prospect_Landing_Zone__r.url__c);
        }
        for(License_and_Certifications__c l : lc)
        {
            l.Lead__c = urlLeads.get(l.Prospect_Landing_Zone__r.url__c);
        }  
        for(Organization__c o : org)
        {
            o.Prospect__c = urlLeads.get(o.Prospect_Landing_Zone__r.url__c);
        }
        update exp;
        update edu;
        update lc;
        update org;
        update scope;
    }
    public void finish(Database.BatchableContext BC) {
    
    }
}