force-app/main/default/objects/Job_Opening__c/Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Job Opening</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Opening__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full time</fullName>
                <default>true</default>
                <label>Full time</label>
            </value>
            <value>
                <fullName>Part time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Opening__c/fields/Job_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Job_Expiry_Date__c</fullName>
    <inlineHelpText>Job Expiry date</inlineHelpText>
    <label>Job Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Opening__c/fields/Job_Source__c.field-meta.xml
<CustomField>
    <fullName>Job_Source__c</fullName>
    <label>Job Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Linkedin</fullName>
            </value>
            <value>
                <fullName>Indeed</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>EdJoin</fullName>
            </value>
            <value>
                <fullName>CareerBuilder</fullName>
            </value>
            <value>
                <fullName>School Spring</fullName>
            </value>
            <value>
                <fullName>Simply Hired</fullName>
            </value>
            <value>
                <fullName>GLASSDOOR</fullName>
            </value>
            <value>
                <fullName>Usreap</fullName>
            </value>
            <value>
                <fullName>IASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESC_NBC_Job_Controller_Test.cls
@isTest
public class ESC_NBC_Job_Controller_Test {

    @testSetup
    static void setupTestData() {
        Job_Opening__c jobOpeningObj = new Job_Opening__c(
        	Name = 'Candidate Beyrer',
            Job_Title__c = 'Professor, Clinical | Director of Clinical Education, SLP | Speech Language Pathologist',
            Job_Source__c = 'Indeed;Other',
            Employment_Type__c = 'Full time',
            Address__City__s = 'Garden City',
            Address__CountryCode__s = 'US',
            Address__Latitude__s = 40.726768,
            Address__Longitude__s = -73.634295,
            Address__StateCode__s = 'NY',
            Job_Expiry_Date__c = System.Today()
        );
        insert jobOpeningObj;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRadar());
    }
    
    @isTest
    static void getJobOpeningDetailsTest() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRadar());
        test.startTest();
        ESC_NBC_Job_Controller.getSearchLocation('Garden City,NY,United States',10);
        test.stopTest();
    }    
}