force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Interview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Job_Opening__c.field-meta.xml
<CustomField>
    <fullName>Job_Opening__c</fullName>
    <label>Job Opening</label>
    <referenceTo>Job_Opening__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ESC_NBC_Prospect__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Active Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Submission</fullName>
                <default>true</default>
                <label>In Submission</label>
            </value>
            <value>
                <fullName>Submission Completed</fullName>
            </value>
            <value>
                <fullName>Client_Rejected</fullName>
                <label>Client Rejected</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Interview Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Interview Failed</label>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Submit_Sales_Rep</fullName>
                <isActive>false</isActive>
                <label>Submit to Sales Rep</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Submitted to client</fullName>
                <isActive>false</isActive>
                <label>Submitted to client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Opening__c/Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Job Opening</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Opening__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Openings</relationshipLabel>
    <relationshipName>Job_Openings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Opening__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESC_NBC_JobOpeningController.cls
public class ESC_NBC_JobOpeningController {
	@AuraEnabled(cacheable=true)
    public static List<Job_Opening__c> getActiveJobOpeningsForClient(Id clientId) {
        if (String.isBlank(clientId)) return new List<Job_Opening__c>();

        return [
            SELECT Id, Name
            FROM Job_Opening__c
            WHERE Client__c = :clientId
            AND Status__c = 'Active'
            ORDER BY CreatedDate DESC
        ];
    }
    
    @AuraEnabled(cacheable=true)
	public static Interview__c getInterviewInfo(Id interviewId) {
    	return [
            SELECT Id, Prospect__c, Job_Opening__c, Job_Opening__r.Name, Job_Opening__r.Client__c
            FROM Interview__c
            WHERE Id = :interviewId
            LIMIT 1
        ];
	}
    
    
    @AuraEnabled(cacheable=true)
	public static List<Contact> getContactsForClient(Id clientId) {
    	if (String.isBlank(clientId)) return new List<Contact>();

    	return [
            SELECT Id, Name, Email
            FROM Contact
            WHERE AccountId = :clientId
        ];
	}
    
    @AuraEnabled(cacheable=true)
    public static Job_Opening__c getJobOpeningInfo(Id jobOpeningId) {
        return [
            SELECT Id, Name, Client__c
            FROM Job_Opening__c
            WHERE Id = :jobOpeningId
            LIMIT 1
        ];
    }
}