force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>In Touch</fullName>
            </value>
            <value>
                <fullName>Active_Prospect</fullName>
                <label>Active Prospect</label>
            </value>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>These are Prospect records in the data pool that everybody can see and approach</description>
    <label>Prospect (Lead database)</label>
</RecordType>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Interview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/ESC_NBC_Client_Name__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Client_Name__c</fullName>
    <formula>Job_Opening__r.Client__r.Name</formula>
    <label>Client Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/ESC_NBC_Interview_Notes__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Interview_Notes__c</fullName>
    <label>Interview Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the interviewer on the client side</description>
    <inlineHelpText>Put the name of the interviewer on the client side</inlineHelpText>
    <label>Interviewer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job_Opening__c.field-meta.xml
<CustomField>
    <fullName>Job_Opening__c</fullName>
    <label>Job Opening</label>
    <referenceTo>Job_Opening__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ESC_NBC_Prospect__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Active Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ESC_NBC_Prospect__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Submission</fullName>
                <default>true</default>
                <label>In Submission</label>
            </value>
            <value>
                <fullName>Submission Completed</fullName>
            </value>
            <value>
                <fullName>Client_Rejected</fullName>
                <label>Client Rejected</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Interview Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Interview Failed</label>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Submit_Sales_Rep</fullName>
                <isActive>false</isActive>
                <label>Submit to Sales Rep</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Submitted to client</fullName>
                <isActive>false</isActive>
                <label>Submitted to client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Zoom_Interview_Link__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Interview_Link__c</fullName>
    <label>Zoom Interview Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/recordTypes/Interview.recordType-meta.xml
<RecordType>
    <fullName>Interview</fullName>
    <active>true</active>
    <label>Interview</label>
</RecordType>

force-app/main/default/objects/Interview__c/recordTypes/Submission.recordType-meta.xml
<RecordType>
    <fullName>Submission</fullName>
    <active>true</active>
    <label>Submission</label>
</RecordType>

force-app/main/default/objects/Job_Opening__c/Job_Opening__c.object-meta.xml
<CustomObject>
    <label>Job Opening</label>
    <nameField>
        <label>Job Opening</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Opening__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Openings</relationshipLabel>
    <relationshipName>Job_Openings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Opening__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SLP</fullName>
            </value>
            <value>
                <fullName>ABA</fullName>
            </value>
            <value>
                <fullName>BCBA</fullName>
            </value>
            <value>
                <fullName>CF-SLP</fullName>
            </value>
            <value>
                <fullName>CNA</fullName>
            </value>
            <value>
                <fullName>COTA</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Diagnostician</fullName>
            </value>
            <value>
                <fullName>ERMHS Therapist</fullName>
            </value>
            <value>
                <fullName>GN-EDU</fullName>
            </value>
            <value>
                <fullName>LMFT</fullName>
            </value>
            <value>
                <fullName>LMSW</fullName>
            </value>
            <value>
                <fullName>LPC</fullName>
            </value>
            <value>
                <fullName>LPN</fullName>
            </value>
            <value>
                <fullName>LSW</fullName>
            </value>
            <value>
                <fullName>LVN</fullName>
            </value>
            <value>
                <fullName>MFT</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OT-A</fullName>
            </value>
            <value>
                <fullName>Para</fullName>
            </value>
            <value>
                <fullName>PSY</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>PT-A</fullName>
            </value>
            <value>
                <fullName>RBT</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>SKO</fullName>
            </value>
            <value>
                <fullName>SLI</fullName>
            </value>
            <value>
                <fullName>SLP-A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Opening__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESC_NBC_InterviewController.cls
public class ESC_NBC_InterviewController {
	@AuraEnabled
    public static List<Interview__c> getSubmissionForProspect(Id prospectId) {
        return [SELECT Id, Name, Status__c, Interview_Date__c,ESC_NBC_Client_Name__c,Job_Opening__r.Id,Job_Opening__r.Position__c, 
                Job_Opening__r.Client__c, Job_Opening__r.Client__r.Name 
                FROM Interview__c WHERE Prospect__c = :prospectId AND RecordType.DeveloperName = 'Submission'
            ORDER BY Interview_Date__c DESC
        ];
    }
    
    @AuraEnabled
    public static List<Interview__c> getInterviewsForProspect(Id prospectId) {
        return [
            SELECT Id, Name, Status__c, Interview_Date__c,Interviewer_Name__c,Interviewer_Name__r.Name,ESC_NBC_Client_Name__c,Job_Opening__r.Id, 
            Job_Opening__r.Position__c,Job_Opening__r.Client__c, Job_Opening__r.Client__r.Name FROM Interview__c
            WHERE Prospect__c = :prospectId
            AND RecordType.DeveloperName = 'Interview'
            ORDER BY Interview_Date__c DESC
        ];
    }
    
    
    @AuraEnabled
    public static void updateInterviewStatus(Id interviewId, String status, String notes) {
        Interview__c interview = [
            SELECT Id, Status__c, Prospect__c, ESC_NBC_Interview_Notes__c,Interviewer_Name__r.Name
            FROM Interview__c
            WHERE Id = :interviewId
            LIMIT 1
        ];
    
        if (interview != null) {
            interview.Status__c = status;
            interview.ESC_NBC_Interview_Notes__c = notes;
    
            if (interview.Prospect__c != null) {
                // ESC_NBC_Prospect__c prospect = [
                //     SELECT Id, ESC_NBC_Prospect_Status__c
                //     FROM ESC_NBC_Prospect__c
                //     WHERE Id = :interview.Prospect__c
                //     LIMIT 1
                // ];
                // prospect.ESC_NBC_Prospect_Status__c = status;
                // update new List<SObject>{ interview, prospect };
                update new List<SObject>{ interview };
                ESC_NBC_Prospect_Utility.updateProspectStatus(interview.Prospect__c, status);
            } else {
                update interview;
            }
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getRecordTypeInfoResult(){
        Schema.DescribeSObjectResult describeResult = Schema.SObjectType.Interview__c;
        Map<id,Schema.RecordTypeInfo> recordTypeMap= describeResult.getRecordTypeInfosById();
        List<String> recordTypeList = new List<String>();
        for(Schema.RecordTypeInfo info : recordTypeMap.values()){
            if(info.getDeveloperName() != 'Master'){
            recordTypeList.add(info.getRecordTypeId() + '-' + info.getName());
            }
        }
        return recordTypeList;
    }
    
        
    @AuraEnabled
    public static void convertToInterview(Id interviewId, Date interviewDate,String zoomMeetingLink,Id interviewerContactId) {
        Interview__c interview = [
            SELECT Id, Interview_Date__c, Status__c, RecordTypeId ,Zoom_Interview_Link__c,Interviewer_Name__c
            FROM Interview__c 
            WHERE Id = :interviewId 
            LIMIT 1
        ];
    
        
        interview.Interview_Date__c = interviewDate;
    
        
        interview.Status__c = 'Scheduled';
    
       
        interview.RecordTypeId = [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType = 'Interview__c' 
              AND DeveloperName = 'Interview' 
            LIMIT 1
        ].Id;
    
        if (zoomMeetingLink != null) {
            interview.Zoom_Interview_Link__c = zoomMeetingLink;
        }
        if(interviewerContactId != null) {
            interview.Interviewer_Name__c = interviewerContactId;
        }
        update interview;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactsForInterviewAccount(Id interviewId) {
        // Query Account Id from the Interview > Job Opening > Client
        Interview__c interviewWithAccount = [
            SELECT Job_Opening__r.Client__c
            FROM Interview__c
            WHERE Id = :interviewId
            LIMIT 1
        ];
    
        if (interviewWithAccount?.Job_Opening__r?.Client__c == null) {
            return new List<Contact>();
        }
    
        // Query Contacts related to that Client Account
        List<Contact> relatedContacts = [
            SELECT Id, Name 
            FROM Contact 
            WHERE AccountId = :interviewWithAccount.Job_Opening__r.Client__c
            ORDER BY Name
            LIMIT 50
        ];
    
        return relatedContacts;
    }


}