force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Email__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABA</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>BCBA</fullName>
            </value>
            <value>
                <fullName>CNA</fullName>
            </value>
            <value>
                <fullName>COTA</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Diagnostician</fullName>
            </value>
            <value>
                <fullName>Environmental Scientist</fullName>
            </value>
            <value>
                <fullName>ERMHS Therapist</fullName>
            </value>
            <value>
                <fullName>GN-EDU</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Interpreter</fullName>
            </value>
            <value>
                <fullName>Librarian</fullName>
            </value>
            <value>
                <fullName>LMFT</fullName>
            </value>
            <value>
                <fullName>LMSW</fullName>
            </value>
            <value>
                <fullName>LPC</fullName>
            </value>
            <value>
                <fullName>LPN</fullName>
            </value>
            <value>
                <fullName>LSW</fullName>
            </value>
            <value>
                <fullName>LVN</fullName>
            </value>
            <value>
                <fullName>MFT</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OT-A</fullName>
            </value>
            <value>
                <fullName>Para</fullName>
            </value>
            <value>
                <fullName>PSY</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>PT-A</fullName>
            </value>
            <value>
                <fullName>RBT</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Phone__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Speciality__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Speciality__c</fullName>
    <label>Speciality</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audiologist</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>DHH</fullName>
            </value>
            <value>
                <fullName>Eng</fullName>
            </value>
            <value>
                <fullName>Intervention Specialist</fullName>
            </value>
            <value>
                <fullName>Math</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>RSP</fullName>
            </value>
            <value>
                <fullName>Sci</fullName>
            </value>
            <value>
                <fullName>SST</fullName>
            </value>
            <value>
                <fullName>Theatre Education</fullName>
            </value>
            <value>
                <fullName>Transition Specialist</fullName>
            </value>
            <value>
                <fullName>TVI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>These are Prospect records in the data pool that everybody can see and approach</description>
    <label>Prospect (Lead database)</label>
</RecordType>

force-app/main/default/objects/Logs__b/Logs__b.object-meta.xml
<CustomObject>
    <label>Logs</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logs__b/fields/Viewed_At__c.field-meta.xml
<CustomField>
    <fullName>Viewed_At__c</fullName>
    <label>Viewed At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Logs__b/fields/Viewed_By__c.field-meta.xml
<CustomField>
    <fullName>Viewed_By__c</fullName>
    <label>Viewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logs__b/fields/Viewed_Contact__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Contact__c</fullName>
    <label>Viewed Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logs__b/fields/What_Viewed__c.field-meta.xml
<CustomField>
    <fullName>What_Viewed__c</fullName>
    <label>What Viewed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESC_NBC_Prospect_Controller.cls
public class ESC_NBC_Prospect_Controller {

    @AuraEnabled(cacheable=true)
    public static ESC_NBC_Prospect__c getContactDetails(Id prospectId) {        
        ESC_NBC_Prospect__c prospect = [
			SELECT
				Id,
				Name,
				ESC_NBC_Phone__c,
				ESC_NBC_Email__c,
				ESC_NBC_Speciality__c,
				ESC_NBC_Job_Title__c,
                RecordType.Name
			FROM
				ESC_NBC_Prospect__c
			WHERE
				Id = :prospectId
		];
        logUsers(prospectId);
        return prospect;
    }
    
    @AuraEnabled
    public static void logUsers(Id prospectId) {
        Logs__b logRecord = new Logs__b(
            Viewed_By__c = UserInfo.getUserId(),
            Viewed_Contact__c = prospectId,
            Viewed_At__c = System.now(),
            What_Viewed__c = 'Phone and Email'
        );
        
        try {
            if(!test.isrunningtest()) {
				Database.insertImmediate(logRecord);
			}
        } catch (Exception e) {
            System.debug('Error inserting log record: ' + e.getMessage());
        }
    }
	
	@AuraEnabled
    public static Map<String, String> updateContactDetails2(ESC_NBC_Prospect__c prospectData) {
		try{
			update prospectData;
			return null;
		}
		catch(exception e){
			Map<String, String> errorMessage = new Map<String, String>();
			errorMessage.put('Other Error', e.getMessage());
			System.debug('Error' + e.getMessage());
			return errorMessage;
		}
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getPicklistValues() {
        List<String> positionPicklistValues = new List<String>();
        List<String> specialityPicklistValues = new List<String>();
        Map<String, List<String>> picklistMap = new Map<String, List<String>>();
        try {
            Schema.DescribeSObjectResult objDescribe = Schema.getGlobalDescribe().get('ESC_NBC_Prospect__c').getDescribe();
            Schema.DescribeFieldResult fieldDescribe = objDescribe.fields.getMap().get('ESC_NBC_Job_Title__c').getDescribe();
            Schema.DescribeFieldResult fieldDescribe2 = objDescribe.fields.getMap().get('ESC_NBC_Speciality__c').getDescribe();
            
            for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
                positionPicklistValues.add(entry.getLabel());
            }
            for (Schema.PicklistEntry entry : fieldDescribe2.getPicklistValues()) {
                specialityPicklistValues.add(entry.getLabel());
            }
            picklistMap.put('ESC_NBC_Job_Title__c', positionPicklistValues);
            picklistMap.put('ESC_NBC_Speciality__c', specialityPicklistValues);
        } catch (Exception e) {
            System.debug('Error retrieving picklist values: ' + e.getMessage());
        }
        return picklistMap;
    }
}