force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Headline__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Headline__c</fullName>
    <label>Headline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>In Touch</fullName>
            </value>
            <value>
                <fullName>Active_Prospect</fullName>
                <label>Active Prospect</label>
            </value>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ESC_NBC_Prospect__c/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>These are Prospect records in the data pool that everybody can see and approach</description>
    <label>Prospect (Lead database)</label>
</RecordType>

force-app/main/default/classes/ESC_NBC_Prospect_Controller_Test.cls
@isTest
public class ESC_NBC_Prospect_Controller_Test {

    @testSetup
    static void setupTestData() {
        ESC_NBC_Prospect__c prospectObj = new ESC_NBC_Prospect__c(
            Name = 'Candidate Beyrer',
            ESC_NBC_Linkedin_URL__c = 'test/test.com',
            ESC_NBC_Headline__c = 'Professor, Clinical | Director of Clinical Education, SLP | Speech Language Pathologist',
            ESC_NBC_Prospect_Status__c = 'Nurturing',
            ESC_NBC_Address__City__s = 'Garden City',
            ESC_NBC_Address__CountryCode__s = 'US',
            ESC_NBC_Address__Latitude__s = 40.726768,
            ESC_NBC_Address__Longitude__s = -73.634295,
            ESC_NBC_Address__StateCode__s = 'NY',
            RecordTypeId = Schema.SObjectType.ESC_NBC_Prospect__c.getRecordTypeInfosByName().get('Active Prospect').getRecordTypeId()
        );
        insert prospectObj;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRadar());
    }
    
    @isTest
    static void getProspectDetailsTest() {
        ESC_NBC_Prospect__c prospectObj = [SELECT ID FROM ESC_NBC_Prospect__c LIMIT 1];
        ESC_NBC_Prospect_Controller.getContactDetails(prospectObj.Id);
    }
    
    @isTest
    static void updateContactDetails2Test() {
        ESC_NBC_Prospect__c prospectObj = [SELECT ID FROM ESC_NBC_Prospect__c LIMIT 1];
        //prospectObj.ESC_NBC_Active__c = true;
        ESC_NBC_Prospect_Controller.updateContactDetails2(prospectObj);
        //System.assertEquals(prospectObj.ESC_NBC_Active__c ==  true, true);
    }
    
    @isTest
    static void getPicklistValuesTest() {
        Map<String, List<String>> pickMap = ESC_NBC_Prospect_Controller.getPicklistValues();
        System.assertEquals(pickMap != null, true);
    }
    
}