force-app/main/default/objects/ESC_NBC_Prospect__c/ESC_NBC_Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ESC_NBC_Prospect__c/fields/ESC_NBC_Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>ESC_NBC_Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>In Touch</fullName>
            </value>
            <value>
                <fullName>Active_Prospect</fullName>
                <label>Active Prospect</label>
            </value>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESC_NBC_Prospect_Utility.cls
/**
* @File Name : ESC_NBC_Prospect_Utility.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : August 1, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | August 1, 2025 |   | Initial Version
**/

public without sharing class ESC_NBC_Prospect_Utility {

	public static void updateProspectStatus(String prospectId, String status){
		Update new ESC_NBC_Prospect__c(
			Id = prospectId,
			ESC_NBC_Prospect_Status__c = status
		);
	}
}